version: "3.7"
services:
    # imagem micro 01
    api_assas:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - apiassas
        links:
            - db_api_assas

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 6060:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - apiassas

    # mysql micro 01
    db_api_assas:
        container_name: db_api_assas
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3399:3306
        command: mysqld --character-set-server=utf8mb4
                --collation-server=utf8mb4_unicode_ci
                --default-authentication-plugin=mysql_native_password --sql-mode=""
        networks:
            - apiassas



networks:
    apiassas:
        driver: bridge
